language: "ko-KR"

reviews:
  path_instructions:
    - path: "test/**/*.py"
      instructions: |
        pytest 테스트 검증:
        - 모든 테스트가 Given-When-Then 패턴을 엄격히 따르는지 확인
        - Given: 테스트 사전 조건 설정 (fixture, mock 준비)
        - When: 테스트할 동작 실행
        - Then: 결과 검증 (assert 문)
        - 패턴을 따르지 않으면 반드시 수정을 요청하세요.

    - path: "**/*.py"
      instructions: |
        Python 코드 품질 체크리스트:

        보안 (최우선):
        - 환경변수 사용 시 안전한 처리 (os.getenv 기본값 설정, 검증)
        - 비밀키, 토큰, 비밀번호가 하드코딩되지 않았는지
        - SQL 인젝션, XSS, CSRF 등 보안 취약점
        - 파일 업로드 시 확장자 및 크기 검증

        코드 품질:
        - 모든 함수/메서드에 타입 힌트 필수
        - 클래스는 SOLID 원칙 준수 (특히 단일 책임 원칙)
        - 의존성 주입 패턴 사용
        - 복잡도가 높은 함수는 분리 권장

        네이밍 컨벤션:
        - 변수/함수: snake_case
        - 클래스: PascalCase
        - 상수: UPPER_SNAKE_CASE
        - private 메서드: _로 시작
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  path_filters:
    - "!**/__pycache__/**"
    - "!**/.pytest_cache/**"
    - "!**/*.pyc"

auto_review:
  enabled: true
  drafts: false

chat:
  auto_reply: true

tools:
  ruff:
    enabled: true

  github_actions:
    enabled: true

early_access: true

reviews_v2:
  enabled: true
