"""add index on salary_stat.job_id

Revision ID: 137333e4b14a
Revises: 4bb919c4b03c
Create Date: 2025-04-20 22:20:44.732091

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "137333e4b14a"
down_revision: Union[str, None] = "4bb919c4b03c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_salary_stat_job_id"), "salary_stat", ["job_id"], unique=False)
    op.drop_index("uniq_job_years", table_name="salary_stat")
    op.create_unique_constraint("uniq_stat_combo", "salary_stat", ["job_id", "experience", "age_group"])
    op.add_column("salary_submission", sa.Column("age_group", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("salary_submission", "age_group")
    op.drop_constraint("uniq_stat_combo", "salary_stat", type_="unique")
    op.drop_index(op.f("ix_salary_stat_job_id"), table_name="salary_stat")
    op.create_index("uniq_job_years", "salary_stat", ["job_id", "experience"], unique=True)
    # ### end Alembic commands ###
