"""유저 테이블 salaie 오타 수정

Revision ID: 2ecbeb6df1f4
Revises: f88e7b586f70
Create Date: 2025-04-30 20:08:27.620896

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2ecbeb6df1f4"
down_revision: Union[str, None] = "f88e7b586f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
