"""유저 테이블 salaie 오타 수정

Revision ID: 499158777778
Revises: 2ecbeb6df1f4
Create Date: 2025-04-30 20:10:47.652422

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "499158777778"
down_revision: Union[str, None] = "2ecbeb6df1f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_consent_ibfk_1", "user_consent", type_="foreignkey")
    op.create_foreign_key(None, "user_consent", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_consent", type_="foreignkey")
    op.create_foreign_key("user_consent_ibfk_1", "user_consent", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
