"""Job 테이블, unique 설정 변경

Revision ID: 4bb919c4b03c
Revises: b23239d140d5
Create Date: 2025-04-16 19:48:58.086218

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bb919c4b03c"
down_revision: Union[str, None] = "b23239d140d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name", table_name="job")
    op.create_unique_constraint("uniq_job_group_job_name", "job", ["group_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_job_group_job_name", "job", type_="unique")
    op.create_index("name", "job", ["name"], unique=True)
    # ### end Alembic commands ###
