"""연봉 통계치 테이블, 나이대 제거

Revision ID: 974193a231be
Revises: e51005928dc6
Create Date: 2025-05-04 19:00:38.937913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974193a231be"
down_revision: Union[str, None] = "e51005928dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_stat_combo", "salary_stat", type_="unique")
    op.create_unique_constraint("uniq_stat_combo", "salary_stat", ["job_id", "experience"])
    op.drop_column("salary_stat", "age_group")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salary_stat", sa.Column("age_group", mysql.INTEGER(), autoincrement=False, nullable=True, comment="나이대")
    )
    op.drop_constraint("uniq_stat_combo", "salary_stat", type_="unique")
    op.create_unique_constraint("uniq_stat_combo", "salary_stat", ["job_id", "experience", "age_group"])
    # ### end Alembic commands ###
