"""uuid 16바이트 저장

Revision ID: a25b8b71adf6
Revises: d22ec8b90395
Create Date: 2025-05-24 20:24:33.866390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a25b8b71adf6"
down_revision: Union[str, None] = "d22ec8b90395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_consent",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("event", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("agree", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_consent_ibfk_1", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_salary",
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("user_id", mysql.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("job_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("experience", mysql.INTEGER(), autoincrement=False, nullable=False, comment="경력"),
        sa.Column("salary", mysql.INTEGER(), autoincrement=False, nullable=False, comment="연봉"),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], name="user_salary_ibfk_1"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_salary_ibfk_2", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("id", "user_salary", ["id"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("email", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("email", "user", ["email"], unique=True)
    op.create_table(
        "user_profile",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("salary_id", sa.BINARY(length=16), nullable=False),
        sa.Column("age", mysql.INTEGER(), autoincrement=False, nullable=True, comment="나이"),
        sa.Column("gender", mysql.VARCHAR(length=10), nullable=True, comment="성별"),
        sa.Column("save_rate", mysql.INTEGER(), autoincrement=False, nullable=True, comment="저축률"),
        sa.Column("has_car", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment="자동차 보유"),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["salary_id"], ["user_salary.id"], name="user_profile_ibfk_1", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("salary_id", "user_profile", ["salary_id"], unique=True)
    op.create_table(
        "job_group",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("name", "job_group", ["name"], unique=True)
    op.create_table(
        "job",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("group_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("name_en", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["job_group.id"], name="job_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("uniq_job_group_job_name", "job", ["group_id", "name"], unique=True)
    op.create_table(
        "salary_stat",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("experience", mysql.INTEGER(), autoincrement=False, nullable=True, comment="경력"),
        sa.Column("avg", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], name="salary_stat_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("uniq_stat_combo", "salary_stat", ["job_id", "experience"], unique=True)
    op.create_index("ix_salary_stat_job_id", "salary_stat", ["job_id"], unique=False)
    # ### end Alembic commands ###
