"""model 세팅

Revision ID: b23239d140d5
Revises:
Create Date: 2025-04-16 18:17:56.574315

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b23239d140d5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["job_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "salary_stat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("avg", sa.Integer(), nullable=False),
        sa.Column("lower", sa.Integer(), nullable=False),
        sa.Column("upper", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "experience", name="uniq_job_years"),
    )
    op.create_table(
        "salary_submission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("test8")
    op.drop_table("test39")
    op.drop_table("test4")
    op.drop_table("test1")
    op.drop_table("test30")
    op.drop_table("test29")
    op.drop_table("test20")
    op.drop_table("test14")
    op.drop_table("test25")
    op.drop_table("test3")
    op.drop_table("test35")
    op.drop_table("test27")
    op.drop_table("test7")
    op.drop_table("test36")
    op.drop_table("test32")
    op.drop_table("test38")
    op.drop_table("test13")
    op.drop_table("test40")
    op.drop_table("test31")
    op.drop_table("test19")
    op.drop_table("test37")
    op.drop_table("test16")
    op.drop_table("test10")
    op.drop_table("test11")
    op.drop_table("test22")
    op.drop_table("test24")
    op.drop_table("test15")
    op.drop_table("test5")
    op.drop_table("test28")
    op.drop_table("test33")
    op.drop_table("test21")
    op.drop_table("test23")
    op.drop_table("test34")
    op.drop_table("test6")
    op.drop_table("test9")
    op.drop_table("test2")
    op.drop_table("test17")
    op.drop_table("test12")
    op.drop_table("test18")
    op.drop_table("test26")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test26",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test18",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test12",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test17",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test2",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test9",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test6",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test34",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test23",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test21",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test33",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test28",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test5",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test15",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test24",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test22",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test11",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test10",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test16",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test37",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test19",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test31",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test40",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test13",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test38",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test32",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test36",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test7",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test27",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test35",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test3",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test25",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test14",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test20",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test29",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test30",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test1",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test4",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test39",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "test8",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("salary_submission")
    op.drop_table("salary_stat")
    op.drop_table("job")
    op.drop_table("job_group")
    # ### end Alembic commands ###
