"""Recreate dropped salary_submission table

Revision ID: b98d07514465
Revises: a06474308e68
Create Date: 2025-04-26 15:21:19.880102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b98d07514465"
down_revision: Union[str, None] = "a06474308e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salary_submission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False, comment="경력"),
        sa.Column("salary", sa.Integer(), nullable=False, comment="연봉"),
        sa.Column("age", sa.Integer(), nullable=True, comment="나이"),
        sa.Column("gender", sa.String(length=10), nullable=True, comment="성별"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("salary_stat", "experience", existing_type=mysql.INTEGER(), comment="경력", existing_nullable=True)
    op.alter_column("salary_stat", "age_group", existing_type=mysql.INTEGER(), comment="나이대", existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salary_stat",
        "age_group",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="나이대",
        existing_nullable=True,
    )
    op.alter_column(
        "salary_stat",
        "experience",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="경력",
        existing_nullable=True,
    )
    op.drop_table("salary_submission")
    # ### end Alembic commands ###
