"""유저 테이블 추가

Revision ID: cb208d6c850b
Revises: 137333e4b14a
Create Date: 2025-04-23 14:42:54.299376

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb208d6c850b"
down_revision: Union[str, None] = "137333e4b14a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salary_stat",
        "age_group",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="나이대, enum으로 별도 관리",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salary_stat",
        "age_group",
        existing_type=mysql.INTEGER(),
        comment="나이대, enum으로 별도 관리",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
