"""user_profile 성별 => str 변경

Revision ID: e51005928dc6
Revises: a942af9bc59f
Create Date: 2025-05-01 19:22:48.893970

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e51005928dc6"
down_revision: Union[str, None] = "a942af9bc59f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profile",
        "gender",
        existing_type=mysql.TINYINT(display_width=1),
        type_=sa.String(length=10),
        existing_comment="성별",
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "user_salary", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_salary", type_="unique")
    op.alter_column(
        "user_profile",
        "gender",
        existing_type=sa.String(length=10),
        type_=mysql.TINYINT(display_width=1),
        existing_comment="성별",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
