"""3단계 유저 입력을 고려한 model 변경

Revision ID: f88e7b586f70
Revises: 841eefca5ed0
Create Date: 2025-04-30 19:06:49.034690

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f88e7b586f70"
down_revision: Union[str, None] = "841eefca5ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_salary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False, comment="경력"),
        sa.Column("salary", sa.Integer(), nullable=False, comment="연봉"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("salary_id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True, comment="나이"),
        sa.Column("gender", sa.Boolean(), nullable=True, comment="성별"),
        sa.Column("save_rate", sa.Integer(), nullable=True, comment="저축률"),
        sa.Column("has_car", sa.Boolean(), nullable=True, comment="자동차 보유 여부"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["salary_id"], ["user_salary.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("salary_id"),
    )
    op.drop_table("salary_submission")
    op.drop_table("test1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test1",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("thistime", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "salary_submission",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("experience", mysql.INTEGER(), autoincrement=False, nullable=False, comment="경력"),
        sa.Column("salary", mysql.INTEGER(), autoincrement=False, nullable=False, comment="연봉"),
        sa.Column("save_rate", mysql.INTEGER(), autoincrement=False, nullable=False, comment="저축률"),
        sa.Column("age", mysql.INTEGER(), autoincrement=False, nullable=True, comment="나이"),
        sa.Column("gender", mysql.VARCHAR(length=10), nullable=True, comment="성별"),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(), nullable=True),
        sa.Column("is_deleted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], name="salary_submission_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("user_profile")
    op.drop_table("user_salary")
    # ### end Alembic commands ###
