DEV_POOL_SIZE = 50
DEV_MAX_OVERFLOW = 5
DEV_COLLECT_POOL_SIZE = 5
DEV_COLLECT_MAX_OVERFLOW = 0


PROD_POOL_SIZE = 50
PROD_MAX_OVERFLOW = 5
PROD_COLLECT_POOL_SIZE = 5
PROD_COLLECT_MAX_OVERFLOW = 0


CONNECTION_TIMEOUT_SECOND = 10
POOL_TIMEOUT_SECOND = 7

REDIS_SOCKET_CONNECTION_TIMEOUT_SECOND = 5
