BIGQUERY_PROJECT = "olass-prod"
BIGQUERY_USER_TABLE = f"{BIGQUERY_PROJECT}.datamart.user_profile_daily"
BIGQUERY_JOURNEY_TABLE = f"{BIGQUERY_PROJECT}.datamart.user_journey_daily"
BIGQUERY_ANALYTICS_DATASET = f"{BIGQUERY_PROJECT}.analytics_434750984"
MAX_ROWS_PER_REQUEST = 5000  # 공식 제한은 10,000이지만 절반으로 안전하게 수행

# 환경별 인증 설정
CREDENTIALS_ENV_VAR = "PROD_BIGQUERY_CREDENTIALS_JSON"
